#!/bin/sh

#DOWNLOAD=ONCE for downloading the file pci.lod from the Motorola OnCE debugger
#DOWNLOAD=ROM for generating a ROM for installation on the PCI board

DOWNLOAD=ROM

asm56300 -b -lPCI_SCUBA_build.ls -d DOWNLOAD $DOWNLOAD PCI_SCUBA_build.asm
dsplnk -bPCI_SCUBA_BOOT_CODE.cld -v PCI_SCUBA_build.cln

cldlod PCI_SCUBA_BOOT_CODE.cld > PCI_SCUBA_BOOT_CODE.lod
srec -bs PCI_SCUBA_BOOT_CODE.lod

rm PCI_SCUBA_build.cln
rm *.cln

exit 0
