#!/bin/sh

#DOWNLOAD=ONCE for downloading the file pci.lod from the Motorola OnCE debugger
#DOWNLOAD=ROM for generating a ROM for installation on the PCI board

SRC=build
BASE=U0103

DOWNLOAD=ROM

asm56300 -b -l${SRC}.ls -d DOWNLOAD $DOWNLOAD $SRC.asm
if [ "$?" != "0" ]; then exit 1; fi

dsplnk -b${SRC}.cld -v ${SRC}.cln
if [ "$?" != "0" ]; then exit 1; fi

cldlod ${SRC}.cld > ${BASE}.lod
if [ "$?" != "0" ]; then exit 1; fi

lod2s ${BASE}.lod ${BASE}.s PCI_SCUBA_BUILD 4

exit 0
