#!/bin/bash

ON=183+
addr=2064

cmd="(\$1 != \">\") {on=0} (on==\"1\") {print \$0} (\$1==\"$ON\") {on=1}"

diff ../U0103/U0103.lod U0104.lod | sed 's/\r//g' |sed 's/a/+ /g' | \
	awk "$cmd" | \
	../make_patch $addr > patch_$addr
